export interface IKey {
  title: string;
  code: number;
  effect: boolean;
}

export const keys: IKey[] = [
  { title: 'backspace', code:	8, effect: true },
  { title: 'tab', code:	9, effect: false },
  { title: 'enter', code:	13, effect: true },
  { title: 'shift', code:	16, effect: false },
  { title: 'ctrl', code:	17, effect: false },
  { title: 'alt', code:	18, effect: false },
  { title: 'pause/break', code:	19, effect: false },
  { title: 'caps lock', code:	20, effect: false },
  { title: 'escape', code:	27, effect: false },
  { title: 'page up', code:	33, effect: false },
  { title: 'Space', code:	32, effect: true },
  { title: 'page down', code:	34, effect: false },
  { title: 'end', code:	35, effect: false },
  { title: 'home', code:	36, effect: false },
  { title: 'arrow left', code:	37, effect: false },
  { title: 'arrow up', code:	38, effect: false },
  { title: 'arrow right', code:	39, effect: false },
  { title: 'arrow down', code:	40, effect: false },
  { title: 'print screen', code:	44, effect: false },
  { title: 'insert', code:	45, effect: false },
  { title: 'delete', code:	46, effect: true },
  { title: '0', code:	48, effect: true },
  { title: '1', code:	49, effect: true },
  { title: '2', code:	50, effect: true },
  { title: '3', code:	51, effect: true },
  { title: '4', code:	52, effect: true },
  { title: '5', code:	53, effect: true },
  { title: '6', code:	54, effect: true },
  { title: '7', code:	55, effect: true },
  { title: '8', code:	56, effect: true },
  { title: '9', code:	57, effect: true },
  { title: 'a', code:	65, effect: true },
  { title: 'b', code:	66, effect: true },
  { title: 'c', code:	67, effect: true },
  { title: 'd', code:	68, effect: true },
  { title: 'e', code:	69, effect: true },
  { title: 'f', code:	70, effect: true },
  { title: 'g', code:	71, effect: true },
  { title: 'h', code:	72, effect: true },
  { title: 'i', code:	73, effect: true },
  { title: 'j', code:	74, effect: true },
  { title: 'k', code:	75, effect: true },
  { title: 'l', code:	76, effect: true },
  { title: 'm', code:	77, effect: true },
  { title: 'n', code:	78, effect: true },
  { title: 'o', code:	79, effect: true },
  { title: 'p', code:	80, effect: true },
  { title: 'q', code:	81, effect: true },
  { title: 'r', code:	82, effect: true },
  { title: 's', code:	83, effect: true },
  { title: 't', code:	84, effect: true },
  { title: 'u', code:	85, effect: true },
  { title: 'v', code:	86, effect: true },
  { title: 'w', code:	87, effect: true },
  { title: 'x', code:	88, effect: true },
  { title: 'y', code:	89, effect: true },
  { title: 'z', code:	90, effect: true },
  { title: 'left window key', code:	91, effect: false },
  { title: 'right window key', code:	92, effect: false },
  { title: 'select key', code:	93, effect: false },
  { title: 'numpad 0', code:	96, effect: true },
  { title: 'numpad 1', code:	97, effect: true },
  { title: 'numpad 2', code:	98, effect: true },
  { title: 'numpad 3', code:	99, effect: true },
  { title: 'numpad 4', code:	100, effect: true },
  { title: 'numpad 5', code:	101, effect: true },
  { title: 'numpad 6', code:	102, effect: true },
  { title: 'numpad 7', code:	103, effect: true },
  { title: 'numpad 8', code:	104, effect: true },
  { title: 'numpad 9', code:	105, effect: true },
  { title: 'multiply', code:	106, effect: true },
  { title: 'add', code:	107, effect: true },
  { title: 'subtract', code:	109, effect: true },
  { title: 'decimal point', code:	110, effect: true },
  { title: 'divide', code:	111, effect: true },
  { title: 'f1', code:	112, effect: false },
  { title: 'f2', code:	113, effect: false },
  { title: 'f3', code:	114, effect: false },
  { title: 'f4', code:	115, effect: false },
  { title: 'f5', code:	116, effect: false },
  { title: 'f6', code:	117, effect: false },
  { title: 'f7', code:	118, effect: false },
  { title: 'f8', code:	119, effect: false },
  { title: 'f9', code:	120, effect: false },
  { title: 'f10', code:	121, effect: false },
  { title: 'f11', code:	122, effect: false },
  { title: 'f12', code:	123, effect: false },
  { title: 'num lock', code:	144, effect: false },
  { title: 'scroll lock', code:	145, effect: false },
  { title: 'My Computer (multimedia keyboard)', code:	182, effect: false },
  { title: 'My Calculator (multimedia keyboard)', code:	183, effect: false },
  { title: 'semi-colon', code:	186, effect: true },
  { title: 'equal sign', code:	187, effect: true },
  { title: 'comma', code:	188, effect: true },
  { title: 'dash', code:	189, effect: true },
  { title: 'period', code:	190, effect: true },
  { title: 'forward slash', code:	191, effect: true },
  { title: 'open bracket', code:	219, effect: true },
  { title: 'back slash', code:	220, effect: true },
  { title: 'close braket', code:	221, effect: true },
  { title: 'single quote', code:	222, effect: true },
];